### ISSUE TITLE
output/output-cadit.js does work neither in jscad.app nor on openjscad.xyz

### ISSUE THREAD

**Issue by Hermann-SW** [cookiecad/Openscad-to-JSCAD-converter#6]
Thanks for the great repo, it is no much that is missing.

I copied ```output/output-cadit.js``` for the usage example command into the web app editors and got errors on SHIFT+ENTER.

Then I added this new first line ...
```
const jscad = require('@jscad/modeling')
```
... and this new last line:
```
module.exports = { main }
```
Pressing SHIFT+ENTER then in both web apps just renders and displays honeweb, here for jscad.app:

![image](https://github.com/cookiecad/Openscad-to-JSCAD-converter/assets/12639134/f56c05d1-4c8b-43ee-96e2-b89aa269525f)

**Comment by Hermann-SW** [comment]
As workaround copy output of this command into jscad.app:
```
echo "const jscad = require('@jscad/modeling')" && cat output/output-cadit.js && echo "module.exports = { main }"
```
Working jscad.app [Script URL](https://jscad.app#data:application/gzip;base64,H4sIACljhWYAA+1abW/byBH+rl+x/XA5Knqx5DhBzk7iFtc7IECL9kO/CYZASyuJCUXqlmRi1/B/7zMzS3KXL7JcXK6H4gwkJHdn5+WZ2ZnhUqs0yXL1KVuFa/VeGf1LERkdfP9nHjnbp2sdR8n2++FgUySrPEoTtQ+jJBiqh4EsfVAHE+2jPPqis7G6TdNYhwnucoPLJjV73Ou73BQZFmfqEVKY91W1flXc6rHKDjttcF3dQ+Bam/rupziODnm0GqtDGt9v0wRTxW0arYnZoJZecywSyALL4hZarPKxipJcm0yLAaRCqWe9hvWNwxwqmDTnK9SMcdlHxqSGl9VG1QvZuLX+W5ToUKhqc2uqL3r1qjZ+ug/zHWYrUKMEtuqPmwD0a5hD6kebf5kC8qPNz2GcaYI81tZX/7j9BGsy8FvcXA2ijaoXDuHFvDDgyesDl354NdBgVVMw5ybJY1Ovn1MTfAnjQjy8vidVzs7UxwQCwzj6NzHMijhXoTHhfZ+WtOTHnV59hlwl7FSUqZCwyVPDVvyFGEyjjK9W5pDEKQXYVUCsI/CbXeHyznKZxjrZ5jsMjUZCqxQRApIcvgC50C0iaEGTrnLTQ5HtArKKICT6ISBQ6nHwqBgr4kfcHlSWh4aDaWX0Xie41QkHoeVPy6xccQVmKmL1Qc3UtQqioXr/gZRHnGD1ZT3ygUeIiWcqS72qmYKejB85vEuje+yKKosGA+t5j3KDsA98v8sW+KveGq2zYDqdhmabkRi7XuYDcKWJxewGEX0IrClBpF6qvyPCp//8OFRnav52NhyD1LKZZnG00sEcY75Qu71/SrLC6B/TgjbtKk5Xn79GCFJHCYLmkGJTU2iVCsjAFU+GRoccJYOuqBHKdtRw3IIM+o/UfKi+a1CytWAM6GUCAQXJMNY+frpZzDnEmGxSkWHcJcMqInvkiGfSd2omKliBRn+hfCVOsZBbdCocaMqml67NRsas9SHfYeCtfd4h6S2/RmsePAc6PPo1jONlvotWnxOd0fr5tFywD++WWxOt60XzuSBczex0tN3RHju/KFdtojjmZFloId4ggS8Rx9utNqgm1RxPrtK42KMyQO9XY/V6rN6O1ZuxuhgrPOJ/jLyBQezDZBUj1S7TzSbTbOqG8pfHyJlczMZqco5/YDSZjxUe8XTRYLYNDz2c7MxicTNm3S7oShrR9fymRFmvt3oZ6w2BYLlUw3l66Bg1FrLm+G2a5+m+ocxO3y2jJNFmaTDjuPBM9lj2i8mDVwiHipoc5dCNmh5+qc4dajJRVvUypNbgHMuY3BknG4TFWcXSCYy7EPGaLe/IIITE4Fr4b+IU9YQTViO+zlQg4ibCfqhGTKZUUIN8rWbT18ib2DH+rKBaT1PKGQ4uywCrdnG3lvcnaGlj/cziNbKCycmuVnbYerOtEPMHUxQc1gxQ9+i0jNPnqzWxqJBYH6Gmot7k6erCPaARpXMUgrhKD13Of9l2qty4DMosMhATbPkgoV2eYvlozDoBA5rtOjio2jvCbuFFE4zlIEY5d0DC6KTcFsgasxuCg6QJ+BYLGlStvHTdzEWXyMk+KeeWio6faiLO23Jb72N59reyjFF8sLNQULmm1iWVFYYQGGd1GSsSNobJhDiutQBhbu+Jad3ld1WYujeEbGlAuFdB7FS2Sn9yqeYygv7mUsrDdWesTNQcMJC+drfSCC19pP+CHWa4wxBpngL0J8NtRbqVeVohirRSoQUJvyn1oT/WiffPzqRfHb3K/jP7HCH7V0NwJlig1pMDSvtevFAZ3htWO2ZCfYc4SMQNSzI0j9K6siloG/5EzMu+rxYpTl5yP0rJmQR+KF3vYGoj3E6IsFqA8OLcw5hTSmvW8GtGZobm/DvK/f5SSvnNXY/yAVZNSkq7dp9RohAMPCtGpAj2IPewLgTOYwVtV1C9eOFTkox3aAphHlrCHsdf9mUXh5cPvwVN+oA6wcDBrBvJci0Qcu4PvFHEZJmFaCkpy2qWfIA2DfT6oy2j7DacIuko1bMN22zK5qRLWzvXQNpijZiGoMYMds1/6YC2lMm9LSm0T7x6MkKhmM3mR5cgtOhlzF3nG99RTXxmXm3x/xZ3Y3VfVo8GNmG8gQbtNZiS3Nw5Q4WqY8JJ3V3LGlXE/6M47RpHDHYNcwh1TUgUtGe4kzgy4MXsY3Vf3tk8K++wUt863mL5daiqexW4JZQmXEcFkGvWTxcZwYGttjaWFh0vhJ0BUh4+iX/5REpu2YlIjlJ+rV7Nuu54rAILL37VMZFTZ1zf+Sc5qEgOsE+EcR3E9Nrkdz6sXSBdSVtTIh16LnUeWhp5OdP6kVCsvF6uPW63F5u/itmNGF1I+RIIunawf0RCoNHr5g+nwLX24WpsiN8AvcYW/ib4ERqtBvpJAHFW9Px4++0BbKa6b4Igw/fsEPydRaC9dKDopq5+/I6i14Odh5wEYRs++YYQ+C0c8jaOs/Em5jAoTz7AgxFtuWGFtwptLvmMf8ofDdpFnefwBkK6tuqhn22elKf49fd4TX3sc2h1e8yzLb+WNbjXmU4+/oa+7NgFJ7jR5oxnuM/3Vg8b8sL/GHUvj//KuFf5+4+t822d6NeS32cm/L/YQvZw7OmXh+f15ycektnvh3Qo5R9GySHUa6hafgske3q87Zd8a6St/PTZ7c0ML7avag93xAViwv2IcI7X/aZ1YnW7ceO2ooSme1HlJrf+08eqk6A/KkCOr47jzZ8mcHLAXybkXV6GIvoa+3pqP1/t+JOGPYEWcl9aOcXLGt9P+HhEPmzRucpselE+0hk4H42f8k7Y7cofxJc16t7vC2ovPlj7Li0sdeOlnviQ6u5z+d6IXd7K/c0kwW+FQKo5TBA9NUOHgOv2dIjDEXJM98ymmWZ4HKzQNTa0cx7q9OH3n8f2zcTZL61caLPgBfaW6EU1ptTdM/qEJNjPxcuEpRH2Ij9AqQ65VYIfoIQxlKL3JcKi9n3XdgeVhIgPWyciPaj0VonT0Tmt2h+t9aeKUe0i7/FyS0x3ujpeKDrHMcGHrfJDmPc2gU/LHxpN5QRIfjwF5pTBMDON020ga4ZX+LVVgSF9d0gNZ7QH/rEVDsL+AyQqIzimJQAA) exported to clipboard.

**Comment by hrgdavor** [comment]
looks like a rather complex script was converted successfully . woot.

**Comment by napter** [comment]
@Hermann-SW The output-cadit.js is meant to be used in catit.app. One of the other output files can be used directly in jscad.xyz without modifications afterwards.

**Comment by Hermann-SW** [comment]
@napter Thanks for the hint.
You are right, ```output.js``` does work in jscad.app.
But the other file ```output.jscad ``` does not work, with this error:
```
SyntaxError: SyntaxError: /jscad.model.js: 'return' outside of function. (415:0)

  413 | }
  414 |
> 415 | return jscadObjects;
      | ^
```
